os:
  - linux
language: php
php:
  - '7.2'

notifications:
  email:
    on_success: never

before_script:
  - cd back
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'create database numeris_testing;'
  - cp .env.travis .env
  - php artisan migrate:refresh --seed --database testing

script:
  - vendor/bin/phpunit tests/Feature/Auth

deploy:
  provider: script
  skip_cleanup: true
  script: git push numeris-isep.fr production
  on:
    branch: production

