os:
  - linux
language: php
php:
  - '7.2'

before_script:
  - cd back
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'create database numeris_testing;'
  - cp .env.travis .env
  - php artisan migrate:refresh --seed --database testing

script:
  - vendor/bin/phpunit tests/Feature/Auth

