version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris_testing'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: numeris_mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: testing
      DB_HOST_TESTING: mysql
      DB_PORT_TESTING: 3306
      DB_DATABASE_TESTING: numeris_testing
      DB_USERNAME_TESTING: root
      DB_PASSWORD_TESTING:
    ports:
      - 8080:80
    links:
      - mysql
    depends_on:
      - mysql
    container_name: numeris_back
