version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql:db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.env
    volumes:
      - ./back:/home/numeris
      - /home/numeris/vendor
      - /home/numeris/public
    ports:
      - ${BACK_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/home/numeris/src
      - /home/numeris/node_modules
    links:
      - back
    expose:
      - ${FRONT_PORT}
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    command: ng s --host 0.0.0.0
