version: '3'
services:

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.production
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    ports:
      - ${BACK_PORT}:80
    container_name: numeris_back
