version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "3000:80"
    links:
      - mysql:db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris-v2'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.env
    environment:
      DB_HOST: 'mysql'
      DB_PORT: 3306
      DB_DATABASE: 'numeris-v2'
      DB_USERNAME: 'root'
      DB_PASSWORD: ''
    volumes:
      - ./back:/home/numeris
      - /home/numeris/vendor
      - /home/numeris/public
    ports:
      - "8080:80"
    links:
      - mysql
    depends_on:
      - mysql
