version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris-v2'
    container_name: numeris_mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.env.travis
    environment:
      DB_PORT: 3306
      DB_DATABASE: numeris-v2
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./back:/home/numeris
      - /home/numeris/vendor
      - /home/numeris/public
    ports:
      - 8080:80
    links:
      - mysql
    depends_on:
      - mysql
    container_name: numeris_back
