version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql
    container_name: numeris_phpmyadmin

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris-v2-testing'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: numeris_mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.env.testing
    environment:
      DB_CONNECTION: testing
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: numeris-v2-testing
      DB_USERNAME: root
      DB_PASSWORD:
    volumes:
      - ./back:/home/numeris
    ports:
      - 8080:80
    links:
      - mysql
    depends_on:
      - mysql
    container_name: numeris_back
