os:
  - linux
language: php
php:
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'create database numeris-v2-testing'
  - cp .env.travis .env
  - php artisan migrate:refresh --seed --database testing

script:
  - vendor/bin/phpunit

